/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.ScrollPaneConstants;

/**
 *
 * @author sandaruwan
 */
public class Attendance extends javax.swing.JPanel {

    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();
        AttendanceScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AttendanceScrollPane2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AttendancePanel = new javax.swing.JPanel();
        AttendancePanelHeader = new javax.swing.JPanel();
        jLabel203 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        AttendanceTabbedPane = new javax.swing.JTabbedPane();
        AttendanceTabbedPaneRoot1 = new javax.swing.JPanel();
        AttendanceScrollPane1 = new javax.swing.JScrollPane();
        AttendancePanelBody1 = new javax.swing.JPanel();
        detailGroup25 = new javax.swing.JPanel();
        jLabel207 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jComboBox79 = new javax.swing.JComboBox<>();
        jComboBox91 = new javax.swing.JComboBox<>();
        jComboBox76 = new javax.swing.JComboBox<>();
        detailGroup26 = new javax.swing.JPanel();
        jLabel225 = new javax.swing.JLabel();
        jLabel226 = new javax.swing.JLabel();
        jComboBox73 = new javax.swing.JComboBox<>();
        detailGroup27 = new javax.swing.JPanel();
        jLabel235 = new javax.swing.JLabel();
        jLabel236 = new javax.swing.JLabel();
        jComboBox95 = new javax.swing.JComboBox<>();
        detailGroup29 = new javax.swing.JPanel();
        jLabel243 = new javax.swing.JLabel();
        jLabel244 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jTextField43 = new javax.swing.JTextField();
        AtendanceMarkPane = new javax.swing.JPanel();
        jLabel205 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton47 = new javax.swing.JButton();
        jLabel209 = new javax.swing.JLabel();
        jLabel221 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        AttendanceTabbedPaneRoot2 = new javax.swing.JPanel();
        AttendanceScrollPane2 = new javax.swing.JScrollPane();
        AttendancePanelBody2 = new javax.swing.JPanel();
        jScrollPane39 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();

        jLabel203.setFont(new java.awt.Font("Raleway Thin", 1, 24)); // NOI18N
        jLabel203.setText("Attendance");

        jLabel204.setText("Tracking Student Attendance: Monitoring Engagement and Participation");

        javax.swing.GroupLayout AttendancePanelHeaderLayout = new javax.swing.GroupLayout(AttendancePanelHeader);
        AttendancePanelHeader.setLayout(AttendancePanelHeaderLayout);
        AttendancePanelHeaderLayout.setHorizontalGroup(
            AttendancePanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendancePanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AttendancePanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel204)
                    .addComponent(jLabel203))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AttendancePanelHeaderLayout.setVerticalGroup(
            AttendancePanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendancePanelHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel203)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel204, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel207.setText("Select Class Date");

        jLabel208.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel208.setText("Date");

        jButton29.setText("Find");

        jComboBox79.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        jComboBox91.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox76.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        javax.swing.GroupLayout detailGroup25Layout = new javax.swing.GroupLayout(detailGroup25);
        detailGroup25.setLayout(detailGroup25Layout);
        detailGroup25Layout.setHorizontalGroup(
            detailGroup25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup25Layout.createSequentialGroup()
                .addComponent(jLabel208)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(detailGroup25Layout.createSequentialGroup()
                .addGroup(detailGroup25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailGroup25Layout.createSequentialGroup()
                        .addComponent(jComboBox91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox79, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel207))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox76, 0, 84, Short.MAX_VALUE)
                    .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        detailGroup25Layout.setVerticalGroup(
            detailGroup25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup25Layout.createSequentialGroup()
                .addComponent(jLabel208)
                .addGap(7, 7, 7)
                .addGroup(detailGroup25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel207, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(detailGroup25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox91, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox79, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox76, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel225.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel225.setText("Course");

        jLabel226.setText("Select Course");

        jComboBox73.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 1", "Course 2", "Course 3" }));

        javax.swing.GroupLayout detailGroup26Layout = new javax.swing.GroupLayout(detailGroup26);
        detailGroup26.setLayout(detailGroup26Layout);
        detailGroup26Layout.setHorizontalGroup(
            detailGroup26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox73, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup26Layout.createSequentialGroup()
                .addComponent(jLabel225)
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(detailGroup26Layout.createSequentialGroup()
                .addComponent(jLabel226)
                .addGap(0, 199, Short.MAX_VALUE))
        );
        detailGroup26Layout.setVerticalGroup(
            detailGroup26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup26Layout.createSequentialGroup()
                .addComponent(jLabel225)
                .addGap(20, 20, 20)
                .addComponent(jLabel226, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox73, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel235.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel235.setText("Subject");

        jLabel236.setText("Select Course Subject");

        jComboBox95.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subject 1", "Subject 2", "Subject 3" }));

        javax.swing.GroupLayout detailGroup27Layout = new javax.swing.GroupLayout(detailGroup27);
        detailGroup27.setLayout(detailGroup27Layout);
        detailGroup27Layout.setHorizontalGroup(
            detailGroup27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox95, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup27Layout.createSequentialGroup()
                .addGroup(detailGroup27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel236)
                    .addComponent(jLabel235))
                .addGap(0, 163, Short.MAX_VALUE))
        );
        detailGroup27Layout.setVerticalGroup(
            detailGroup27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup27Layout.createSequentialGroup()
                .addComponent(jLabel235)
                .addGap(20, 20, 20)
                .addComponent(jLabel236)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox95, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel243.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel243.setText("Class");

        jLabel244.setText("Select Class");

        jButton30.setText("Find");

        jTextField43.setText("Tyep Class ID");

        javax.swing.GroupLayout detailGroup29Layout = new javax.swing.GroupLayout(detailGroup29);
        detailGroup29.setLayout(detailGroup29Layout);
        detailGroup29Layout.setHorizontalGroup(
            detailGroup29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup29Layout.createSequentialGroup()
                .addGroup(detailGroup29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel244)
                    .addComponent(jLabel243))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(detailGroup29Layout.createSequentialGroup()
                .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );
        detailGroup29Layout.setVerticalGroup(
            detailGroup29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup29Layout.createSequentialGroup()
                .addComponent(jLabel243)
                .addGap(20, 20, 20)
                .addComponent(jLabel244)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AtendanceMarkPane.setBackground(new java.awt.Color(43, 48, 55));

        jLabel205.setFont(new java.awt.Font("Raleway Thin", 1, 20)); // NOI18N
        jLabel205.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel205.setText("Attendance Status");

        jLabel206.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel206.setText("Student");

        jButton47.setText("Search");

        jLabel209.setText("Status");

        jLabel221.setText("Method");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "None", "Manual", "Digital", "Barcode", "Biometric" }));

        jCheckBox8.setText("Present");

        jCheckBox9.setText("Absent");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setText("Late");

        jCheckBox11.setText("Excused");

        javax.swing.GroupLayout AtendanceMarkPaneLayout = new javax.swing.GroupLayout(AtendanceMarkPane);
        AtendanceMarkPane.setLayout(AtendanceMarkPaneLayout);
        AtendanceMarkPaneLayout.setHorizontalGroup(
            AtendanceMarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel205, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AtendanceMarkPaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(AtendanceMarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtendanceMarkPaneLayout.createSequentialGroup()
                        .addComponent(jCheckBox8)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox9)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox10)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox11))
                    .addComponent(jLabel209))
                .addGap(164, 164, 164)
                .addGroup(AtendanceMarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AtendanceMarkPaneLayout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton47))
                    .addComponent(jLabel206, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AtendanceMarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AtendanceMarkPaneLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel221)))
                .addGap(31, 31, 31))
        );
        AtendanceMarkPaneLayout.setVerticalGroup(
            AtendanceMarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtendanceMarkPaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel205)
                .addGap(30, 30, 30)
                .addGroup(AtendanceMarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AtendanceMarkPaneLayout.createSequentialGroup()
                        .addComponent(jLabel221)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addGroup(AtendanceMarkPaneLayout.createSequentialGroup()
                        .addComponent(jLabel206)
                        .addGap(18, 18, 18)
                        .addGroup(AtendanceMarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jButton47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(AtendanceMarkPaneLayout.createSequentialGroup()
                        .addComponent(jLabel209)
                        .addGap(18, 18, 18)
                        .addGroup(AtendanceMarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox11))))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AttendancePanelBody1Layout = new javax.swing.GroupLayout(AttendancePanelBody1);
        AttendancePanelBody1.setLayout(AttendancePanelBody1Layout);
        AttendancePanelBody1Layout.setHorizontalGroup(
            AttendancePanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendancePanelBody1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AttendancePanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AtendanceMarkPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AttendancePanelBody1Layout.createSequentialGroup()
                        .addComponent(detailGroup25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(detailGroup26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(detailGroup27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(detailGroup29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        AttendancePanelBody1Layout.setVerticalGroup(
            AttendancePanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendancePanelBody1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AttendancePanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(detailGroup25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailGroup29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailGroup27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailGroup26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AtendanceMarkPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );

        AttendanceScrollPane1.setViewportView(AttendancePanelBody1);

        javax.swing.GroupLayout AttendanceTabbedPaneRoot1Layout = new javax.swing.GroupLayout(AttendanceTabbedPaneRoot1);
        AttendanceTabbedPaneRoot1.setLayout(AttendanceTabbedPaneRoot1Layout);
        AttendanceTabbedPaneRoot1Layout.setHorizontalGroup(
            AttendanceTabbedPaneRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttendanceTabbedPaneRoot1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AttendanceScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AttendanceTabbedPaneRoot1Layout.setVerticalGroup(
            AttendanceTabbedPaneRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttendanceTabbedPaneRoot1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(AttendanceScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AttendanceTabbedPane.addTab("Student", AttendanceTabbedPaneRoot1);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane39.setViewportView(jTable7);

        javax.swing.GroupLayout AttendancePanelBody2Layout = new javax.swing.GroupLayout(AttendancePanelBody2);
        AttendancePanelBody2.setLayout(AttendancePanelBody2Layout);
        AttendancePanelBody2Layout.setHorizontalGroup(
            AttendancePanelBody2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendancePanelBody2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        AttendancePanelBody2Layout.setVerticalGroup(
            AttendancePanelBody2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendancePanelBody2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        AttendanceScrollPane2.setViewportView(AttendancePanelBody2);

        javax.swing.GroupLayout AttendanceTabbedPaneRoot2Layout = new javax.swing.GroupLayout(AttendanceTabbedPaneRoot2);
        AttendanceTabbedPaneRoot2.setLayout(AttendanceTabbedPaneRoot2Layout);
        AttendanceTabbedPaneRoot2Layout.setHorizontalGroup(
            AttendanceTabbedPaneRoot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttendanceTabbedPaneRoot2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AttendanceScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AttendanceTabbedPaneRoot2Layout.setVerticalGroup(
            AttendanceTabbedPaneRoot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttendanceTabbedPaneRoot2Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(AttendanceScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AttendanceTabbedPane.addTab("View Details", AttendanceTabbedPaneRoot2);

        javax.swing.GroupLayout AttendancePanelLayout = new javax.swing.GroupLayout(AttendancePanel);
        AttendancePanel.setLayout(AttendancePanelLayout);
        AttendancePanelLayout.setHorizontalGroup(
            AttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AttendancePanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AttendancePanelLayout.createSequentialGroup()
                .addComponent(AttendanceTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AttendancePanelLayout.setVerticalGroup(
            AttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendancePanelLayout.createSequentialGroup()
                .addComponent(AttendancePanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AttendanceTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1329, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AttendancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AttendancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AtendanceMarkPane;
    private javax.swing.JPanel AttendancePanel;
    private javax.swing.JPanel AttendancePanelBody1;
    private javax.swing.JPanel AttendancePanelBody2;
    private javax.swing.JPanel AttendancePanelHeader;
    private javax.swing.JScrollPane AttendanceScrollPane1;
    private javax.swing.JScrollPane AttendanceScrollPane2;
    private javax.swing.JTabbedPane AttendanceTabbedPane;
    private javax.swing.JPanel AttendanceTabbedPaneRoot1;
    private javax.swing.JPanel AttendanceTabbedPaneRoot2;
    private javax.swing.JPanel detailGroup25;
    private javax.swing.JPanel detailGroup26;
    private javax.swing.JPanel detailGroup27;
    private javax.swing.JPanel detailGroup29;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton47;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox73;
    private javax.swing.JComboBox<String> jComboBox76;
    private javax.swing.JComboBox<String> jComboBox79;
    private javax.swing.JComboBox<String> jComboBox91;
    private javax.swing.JComboBox<String> jComboBox95;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel225;
    private javax.swing.JLabel jLabel226;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel243;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
