/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.ScrollPaneConstants;

/**
 *
 * @author sandaruwan
 */
public class Enrollment extends javax.swing.JPanel {

    /**
     * Creates new form Enrollment
     */
    public Enrollment() {
        initComponents();
        EnrollmentsScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        EnrollmentsScrollPane2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DocumentSubmissionBtnGroup = new javax.swing.ButtonGroup();
        CourseCompletedStatusBtnGroup = new javax.swing.ButtonGroup();
        EnrollmentTypeBtnGroup = new javax.swing.ButtonGroup();
        EnrollmentsPanel = new javax.swing.JPanel();
        EnrollmentsPanelHeader = new javax.swing.JPanel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        EnrollmentsTabbedPane = new javax.swing.JTabbedPane();
        EnrollmentsTabbedPaneRoot1 = new javax.swing.JPanel();
        EnrollmentsScrollPane1 = new javax.swing.JScrollPane();
        EnrollmentsPanelBody1 = new javax.swing.JPanel();
        detailGroup21 = new javax.swing.JPanel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jButton26 = new javax.swing.JButton();
        jLabel213 = new javax.swing.JLabel();
        jComboBox22 = new javax.swing.JComboBox<>();
        jComboBox89 = new javax.swing.JComboBox<>();
        jComboBox70 = new javax.swing.JComboBox<>();
        jComboBox23 = new javax.swing.JComboBox<>();
        jLabel214 = new javax.swing.JLabel();
        jComboBox24 = new javax.swing.JComboBox<>();
        jLabel219 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jButton27 = new javax.swing.JButton();
        jComboBox30 = new javax.swing.JComboBox<>();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        detailGroup22 = new javax.swing.JPanel();
        jLabel195 = new javax.swing.JLabel();
        jLabel197 = new javax.swing.JLabel();
        jComboBox71 = new javax.swing.JComboBox<>();
        jLabel198 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jComboBox82 = new javax.swing.JComboBox<>();
        jComboBox81 = new javax.swing.JComboBox<>();
        jComboBox80 = new javax.swing.JComboBox<>();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel196 = new javax.swing.JLabel();
        jLabel200 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jScrollPane32 = new javax.swing.JScrollPane();
        jTextArea29 = new javax.swing.JTextArea();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        jComboBox31 = new javax.swing.JComboBox<>();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel194 = new javax.swing.JLabel();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jComboBox32 = new javax.swing.JComboBox<>();
        detailGroup23 = new javax.swing.JPanel();
        jLabel210 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jComboBox83 = new javax.swing.JComboBox<>();
        jTextField45 = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jComboBox84 = new javax.swing.JComboBox<>();
        jLabel215 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jComboBox27 = new javax.swing.JComboBox<>();
        jTextField47 = new javax.swing.JTextField();
        jComboBox85 = new javax.swing.JComboBox<>();
        jLabel216 = new javax.swing.JLabel();
        jLabel217 = new javax.swing.JLabel();
        jComboBox86 = new javax.swing.JComboBox<>();
        jTextField48 = new javax.swing.JTextField();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jLabel218 = new javax.swing.JLabel();
        jComboBox29 = new javax.swing.JComboBox<>();
        detailGroup24 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jTextField46 = new javax.swing.JTextField();
        jLabel212 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        EnrollmentsTabbedPaneRoot2 = new javax.swing.JPanel();
        EnrollmentsScrollPane2 = new javax.swing.JScrollPane();
        EnrollmentsPanelBody2 = new javax.swing.JPanel();
        jScrollPane38 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();

        jLabel152.setFont(new java.awt.Font("Raleway Thin", 1, 24)); // NOI18N
        jLabel152.setText("Enrollments Management");

        jLabel153.setText("Optimizing Enrollments Management: Add, Remove, Update, and Search with Ease");

        javax.swing.GroupLayout EnrollmentsPanelHeaderLayout = new javax.swing.GroupLayout(EnrollmentsPanelHeader);
        EnrollmentsPanelHeader.setLayout(EnrollmentsPanelHeaderLayout);
        EnrollmentsPanelHeaderLayout.setHorizontalGroup(
            EnrollmentsPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollmentsPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnrollmentsPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel153)
                    .addComponent(jLabel152))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        EnrollmentsPanelHeaderLayout.setVerticalGroup(
            EnrollmentsPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollmentsPanelHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel152)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel153, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel154.setText("Date and semester of enrollment");

        jLabel155.setText("Course");

        jLabel158.setText("Select Student");

        jLabel159.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel159.setText("Student Information");

        jLabel160.setText("Batch");

        jTextField33.setText("type student mobile");

        jButton26.setText("Find");

        jLabel213.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel213.setText("Academic Information");

        jComboBox22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 1", "Course 2", "Course 3", "Course 4" }));

        jComboBox89.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jComboBox70.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1", "Semester 2", "Semester 3" }));

        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bison", "Shire Horse", "Shark" }));

        jLabel214.setText("Academic Officer");

        jComboBox24.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Officer 1", "Officer 2", "Officer 3" }));

        jLabel219.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel219.setText("Document Submission");

        jLabel220.setText("Documents required for enrollment");

        jButton27.setText("Add");

        jComboBox30.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Document 1", "Transcript", "Identification documents" }));

        jRadioButton12.setText("Submitted");

        jRadioButton13.setText("Pending");

        jRadioButton14.setText("Verified");

        javax.swing.GroupLayout detailGroup21Layout = new javax.swing.GroupLayout(detailGroup21);
        detailGroup21.setLayout(detailGroup21Layout);
        detailGroup21Layout.setHorizontalGroup(
            detailGroup21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup21Layout.createSequentialGroup()
                .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
            .addComponent(jComboBox22, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup21Layout.createSequentialGroup()
                .addGroup(detailGroup21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel154)
                    .addComponent(jLabel155)
                    .addComponent(jLabel158)
                    .addComponent(jLabel159))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jComboBox23, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBox24, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup21Layout.createSequentialGroup()
                .addComponent(jComboBox89, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox70, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailGroup21Layout.createSequentialGroup()
                .addComponent(jTextField41)
                .addGap(18, 18, 18)
                .addComponent(jButton27))
            .addComponent(jComboBox30, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup21Layout.createSequentialGroup()
                .addGroup(detailGroup21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel160)
                    .addComponent(jLabel213)
                    .addComponent(jLabel214)
                    .addComponent(jLabel219)
                    .addComponent(jLabel220))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(detailGroup21Layout.createSequentialGroup()
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton13)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton14))
        );
        detailGroup21Layout.setVerticalGroup(
            detailGroup21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup21Layout.createSequentialGroup()
                .addComponent(jLabel159)
                .addGap(20, 20, 20)
                .addComponent(jLabel158, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField33, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jLabel213)
                .addGap(20, 20, 20)
                .addComponent(jLabel155)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel154, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox89, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox70, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel160)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel214)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel219)
                .addGap(20, 20, 20)
                .addComponent(jLabel220)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(detailGroup21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton14))
                .addGap(65, 65, 65))
        );

        jLabel195.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel195.setText("Enrollment Details");

        jLabel197.setText("Enrollment date");

        jComboBox71.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved", "Rejected" }));

        jLabel198.setText("Enrollment status");

        jLabel199.setText("Enrollment type");

        jComboBox82.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jComboBox81.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        jComboBox80.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jRadioButton8.setText("Full-Time");

        jRadioButton9.setText("Part-Time");

        jLabel196.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel196.setText("Prerequisites and Restrictions");

        jLabel200.setText("Requirements for enrollment");

        jTextArea16.setColumns(20);
        jTextArea16.setRows(5);
        jScrollPane19.setViewportView(jTextArea16);

        jTextArea29.setColumns(20);
        jTextArea29.setRows(5);
        jScrollPane32.setViewportView(jTextArea29);

        jLabel201.setText("Limitations");

        jLabel202.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel202.setText("Enrollment History");

        jLabel193.setText("Course");

        jComboBox31.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 1", "Course 2", "Course 3", "Course 4" }));

        jRadioButton15.setText("Completed");

        jRadioButton16.setText("Incomplete");

        jLabel194.setText("Completed Subjects");

        jRadioButton23.setText("Incomplete");

        jRadioButton24.setText("Completed");

        jComboBox32.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subject 1", "Subject 2", "Subject 3", "Subject 4" }));

        javax.swing.GroupLayout detailGroup22Layout = new javax.swing.GroupLayout(detailGroup22);
        detailGroup22.setLayout(detailGroup22Layout);
        detailGroup22Layout.setHorizontalGroup(
            detailGroup22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox71, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup22Layout.createSequentialGroup()
                .addComponent(jComboBox80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox81, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox82, 0, 84, Short.MAX_VALUE))
            .addGroup(detailGroup22Layout.createSequentialGroup()
                .addComponent(jLabel195)
                .addContainerGap(136, Short.MAX_VALUE))
            .addComponent(jScrollPane19)
            .addComponent(jScrollPane32)
            .addComponent(jComboBox31, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBox32, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup22Layout.createSequentialGroup()
                .addGroup(detailGroup22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel199)
                    .addComponent(jLabel198)
                    .addComponent(jLabel197)
                    .addGroup(detailGroup22Layout.createSequentialGroup()
                        .addComponent(jRadioButton8)
                        .addGap(40, 40, 40)
                        .addComponent(jRadioButton9))
                    .addComponent(jLabel196)
                    .addComponent(jLabel200)
                    .addComponent(jLabel201)
                    .addComponent(jLabel202)
                    .addComponent(jLabel193)
                    .addGroup(detailGroup22Layout.createSequentialGroup()
                        .addComponent(jRadioButton15)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButton16))
                    .addComponent(jLabel194)
                    .addGroup(detailGroup22Layout.createSequentialGroup()
                        .addComponent(jRadioButton24)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButton23)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        detailGroup22Layout.setVerticalGroup(
            detailGroup22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup22Layout.createSequentialGroup()
                .addComponent(jLabel195)
                .addGap(20, 20, 20)
                .addComponent(jLabel197, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox80, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox82, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel198, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox71, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel199, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9))
                .addGap(30, 30, 30)
                .addComponent(jLabel196)
                .addGap(20, 20, 20)
                .addComponent(jLabel200, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel201, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel202)
                .addGap(20, 20, 20)
                .addComponent(jLabel193)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(detailGroup22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16))
                .addGap(20, 20, 20)
                .addComponent(jLabel194)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(detailGroup22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton23))
                .addContainerGap())
        );

        jLabel210.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel210.setText("Financial Information");

        jLabel211.setText("Payment");

        jComboBox83.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LKR", "$", "EUR", "GDP" }));

        jButton22.setText("Add");

        jComboBox84.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Payment 1", "Payment 2", "Payment 3" }));

        jLabel215.setText("Price");

        jLabel157.setText("Scholarships");

        jComboBox27.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100%", "75%", "50%", "25%", " " }));

        jComboBox85.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LKR", "$", "EUR", "GDP" }));

        jLabel216.setText("Reduced Amount");

        jLabel217.setText("To Pay");

        jComboBox86.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LKR", "$", "EUR", "GDP" }));

        jRadioButton10.setText("Yes");

        jRadioButton11.setText("No");

        jLabel218.setText("Payment status");

        jComboBox29.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout detailGroup23Layout = new javax.swing.GroupLayout(detailGroup23);
        detailGroup23.setLayout(detailGroup23Layout);
        detailGroup23Layout.setHorizontalGroup(
            detailGroup23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup23Layout.createSequentialGroup()
                .addComponent(jComboBox83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField45))
            .addComponent(jComboBox84, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup23Layout.createSequentialGroup()
                .addComponent(jComboBox85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailGroup23Layout.createSequentialGroup()
                .addComponent(jTextField34)
                .addGap(18, 18, 18)
                .addComponent(jButton22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailGroup23Layout.createSequentialGroup()
                .addComponent(jRadioButton10)
                .addGap(50, 50, 50)
                .addComponent(jRadioButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jComboBox27, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup23Layout.createSequentialGroup()
                .addComponent(jComboBox86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField48))
            .addGroup(detailGroup23Layout.createSequentialGroup()
                .addGroup(detailGroup23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel210)
                    .addComponent(jLabel211)
                    .addComponent(jLabel215)
                    .addComponent(jLabel157)
                    .addComponent(jLabel216)
                    .addComponent(jLabel217)
                    .addComponent(jLabel218))
                .addGap(0, 116, Short.MAX_VALUE))
            .addComponent(jComboBox29, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        detailGroup23Layout.setVerticalGroup(
            detailGroup23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup23Layout.createSequentialGroup()
                .addComponent(jLabel210)
                .addGap(20, 20, 20)
                .addComponent(jLabel211)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox84, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel215)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox83, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel157)
                .addGap(20, 20, 20)
                .addGroup(detailGroup23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11))
                .addGap(20, 20, 20)
                .addGroup(detailGroup23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel216)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox85, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel217)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox86, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel218)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton23.setText("Add New Enrollment");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("Update Enrollment Details");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setText("Remove Enrollment");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jTextField46.setText("Search Student");
        jTextField46.setToolTipText("Search Students");

        jLabel212.setText("Select Student (To Edit Details)");

        javax.swing.GroupLayout detailGroup24Layout = new javax.swing.GroupLayout(detailGroup24);
        detailGroup24.setLayout(detailGroup24Layout);
        detailGroup24Layout.setHorizontalGroup(
            detailGroup24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(jTextField46, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addGroup(detailGroup24Layout.createSequentialGroup()
                .addComponent(jLabel212)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        detailGroup24Layout.setVerticalGroup(
            detailGroup24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup24Layout.createSequentialGroup()
                .addComponent(jLabel212)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSeparator7.setForeground(new java.awt.Color(65, 77, 87));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout EnrollmentsPanelBody1Layout = new javax.swing.GroupLayout(EnrollmentsPanelBody1);
        EnrollmentsPanelBody1.setLayout(EnrollmentsPanelBody1Layout);
        EnrollmentsPanelBody1Layout.setHorizontalGroup(
            EnrollmentsPanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollmentsPanelBody1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(detailGroup21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(detailGroup22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(detailGroup23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(detailGroup24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        EnrollmentsPanelBody1Layout.setVerticalGroup(
            EnrollmentsPanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollmentsPanelBody1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(EnrollmentsPanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailGroup24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EnrollmentsPanelBody1Layout.createSequentialGroup()
                        .addComponent(detailGroup23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(EnrollmentsPanelBody1Layout.createSequentialGroup()
                        .addGroup(EnrollmentsPanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(detailGroup21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(detailGroup22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(EnrollmentsPanelBody1Layout.createSequentialGroup()
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        EnrollmentsScrollPane1.setViewportView(EnrollmentsPanelBody1);

        javax.swing.GroupLayout EnrollmentsTabbedPaneRoot1Layout = new javax.swing.GroupLayout(EnrollmentsTabbedPaneRoot1);
        EnrollmentsTabbedPaneRoot1.setLayout(EnrollmentsTabbedPaneRoot1Layout);
        EnrollmentsTabbedPaneRoot1Layout.setHorizontalGroup(
            EnrollmentsTabbedPaneRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnrollmentsTabbedPaneRoot1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EnrollmentsScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EnrollmentsTabbedPaneRoot1Layout.setVerticalGroup(
            EnrollmentsTabbedPaneRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnrollmentsTabbedPaneRoot1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(EnrollmentsScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        EnrollmentsTabbedPane.addTab("Student", EnrollmentsTabbedPaneRoot1);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane38.setViewportView(jTable6);

        javax.swing.GroupLayout EnrollmentsPanelBody2Layout = new javax.swing.GroupLayout(EnrollmentsPanelBody2);
        EnrollmentsPanelBody2.setLayout(EnrollmentsPanelBody2Layout);
        EnrollmentsPanelBody2Layout.setHorizontalGroup(
            EnrollmentsPanelBody2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollmentsPanelBody2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        EnrollmentsPanelBody2Layout.setVerticalGroup(
            EnrollmentsPanelBody2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollmentsPanelBody2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        EnrollmentsScrollPane2.setViewportView(EnrollmentsPanelBody2);

        javax.swing.GroupLayout EnrollmentsTabbedPaneRoot2Layout = new javax.swing.GroupLayout(EnrollmentsTabbedPaneRoot2);
        EnrollmentsTabbedPaneRoot2.setLayout(EnrollmentsTabbedPaneRoot2Layout);
        EnrollmentsTabbedPaneRoot2Layout.setHorizontalGroup(
            EnrollmentsTabbedPaneRoot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnrollmentsTabbedPaneRoot2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EnrollmentsScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EnrollmentsTabbedPaneRoot2Layout.setVerticalGroup(
            EnrollmentsTabbedPaneRoot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnrollmentsTabbedPaneRoot2Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(EnrollmentsScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        EnrollmentsTabbedPane.addTab("Teachers", EnrollmentsTabbedPaneRoot2);

        javax.swing.GroupLayout EnrollmentsPanelLayout = new javax.swing.GroupLayout(EnrollmentsPanel);
        EnrollmentsPanel.setLayout(EnrollmentsPanelLayout);
        EnrollmentsPanelLayout.setHorizontalGroup(
            EnrollmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EnrollmentsPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(EnrollmentsPanelLayout.createSequentialGroup()
                .addComponent(EnrollmentsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        EnrollmentsPanelLayout.setVerticalGroup(
            EnrollmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollmentsPanelLayout.createSequentialGroup()
                .addComponent(EnrollmentsPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EnrollmentsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1329, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EnrollmentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EnrollmentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup CourseCompletedStatusBtnGroup;
    private javax.swing.ButtonGroup DocumentSubmissionBtnGroup;
    private javax.swing.ButtonGroup EnrollmentTypeBtnGroup;
    private javax.swing.JPanel EnrollmentsPanel;
    private javax.swing.JPanel EnrollmentsPanelBody1;
    private javax.swing.JPanel EnrollmentsPanelBody2;
    private javax.swing.JPanel EnrollmentsPanelHeader;
    private javax.swing.JScrollPane EnrollmentsScrollPane1;
    private javax.swing.JScrollPane EnrollmentsScrollPane2;
    private javax.swing.JTabbedPane EnrollmentsTabbedPane;
    private javax.swing.JPanel EnrollmentsTabbedPaneRoot1;
    private javax.swing.JPanel EnrollmentsTabbedPaneRoot2;
    private javax.swing.JPanel detailGroup21;
    private javax.swing.JPanel detailGroup22;
    private javax.swing.JPanel detailGroup23;
    private javax.swing.JPanel detailGroup24;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JComboBox<String> jComboBox22;
    private javax.swing.JComboBox<String> jComboBox23;
    private javax.swing.JComboBox<String> jComboBox24;
    private javax.swing.JComboBox<String> jComboBox27;
    private javax.swing.JComboBox<String> jComboBox29;
    private javax.swing.JComboBox<String> jComboBox30;
    private javax.swing.JComboBox<String> jComboBox31;
    private javax.swing.JComboBox<String> jComboBox32;
    private javax.swing.JComboBox<String> jComboBox70;
    private javax.swing.JComboBox<String> jComboBox71;
    private javax.swing.JComboBox<String> jComboBox80;
    private javax.swing.JComboBox<String> jComboBox81;
    private javax.swing.JComboBox<String> jComboBox82;
    private javax.swing.JComboBox<String> jComboBox83;
    private javax.swing.JComboBox<String> jComboBox84;
    private javax.swing.JComboBox<String> jComboBox85;
    private javax.swing.JComboBox<String> jComboBox86;
    private javax.swing.JComboBox<String> jComboBox89;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea29;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    // End of variables declaration//GEN-END:variables
}
