/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.ScrollPaneConstants;

/**
 *
 * @author sandaruwan
 */
public class Report extends javax.swing.JPanel {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        ReportsScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ReportsScrollPane2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReportsPanel = new javax.swing.JPanel();
        ReportsPanelHeader = new javax.swing.JPanel();
        jLabel242 = new javax.swing.JLabel();
        jLabel247 = new javax.swing.JLabel();
        ReportsTabbedPane = new javax.swing.JTabbedPane();
        ReportsTabbedPaneRoot1 = new javax.swing.JPanel();
        ReportsScrollPane1 = new javax.swing.JScrollPane();
        ReportsPanelBody1 = new javax.swing.JPanel();
        detailGroup33 = new javax.swing.JPanel();
        jLabel248 = new javax.swing.JLabel();
        jLabel249 = new javax.swing.JLabel();
        jTextField50 = new javax.swing.JTextField();
        jButton33 = new javax.swing.JButton();
        detailGroup34 = new javax.swing.JPanel();
        jLabel250 = new javax.swing.JLabel();
        jLabel251 = new javax.swing.JLabel();
        jComboBox75 = new javax.swing.JComboBox<>();
        detailGroup35 = new javax.swing.JPanel();
        jLabel252 = new javax.swing.JLabel();
        jLabel253 = new javax.swing.JLabel();
        jComboBox101 = new javax.swing.JComboBox<>();
        detailGroup36 = new javax.swing.JPanel();
        jLabel254 = new javax.swing.JLabel();
        jLabel255 = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        jTextField51 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel256 = new javax.swing.JLabel();
        jLabel257 = new javax.swing.JLabel();
        jLabel258 = new javax.swing.JLabel();
        jLabel259 = new javax.swing.JLabel();
        jLabel260 = new javax.swing.JLabel();
        jLabel261 = new javax.swing.JLabel();
        jComboBox102 = new javax.swing.JComboBox<>();
        jComboBox103 = new javax.swing.JComboBox<>();
        jComboBox104 = new javax.swing.JComboBox<>();
        jComboBox105 = new javax.swing.JComboBox<>();
        ReportsTabbedPaneRoot2 = new javax.swing.JPanel();
        ReportsScrollPane2 = new javax.swing.JScrollPane();
        ReportsPanelBody2 = new javax.swing.JPanel();
        jScrollPane41 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();

        jLabel242.setFont(new java.awt.Font("Raleway Thin", 1, 24)); // NOI18N
        jLabel242.setText("Reports");

        jLabel247.setText("Insights and Analytics: Comprehensive Reports for Student Performance and Progress");

        javax.swing.GroupLayout ReportsPanelHeaderLayout = new javax.swing.GroupLayout(ReportsPanelHeader);
        ReportsPanelHeader.setLayout(ReportsPanelHeaderLayout);
        ReportsPanelHeaderLayout.setHorizontalGroup(
            ReportsPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReportsPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel247)
                    .addComponent(jLabel242))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ReportsPanelHeaderLayout.setVerticalGroup(
            ReportsPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsPanelHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel242)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel247, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel248.setText("Select Student");

        jLabel249.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel249.setText("Student");

        jTextField50.setText("type student mobile");

        jButton33.setText("Find");

        javax.swing.GroupLayout detailGroup33Layout = new javax.swing.GroupLayout(detailGroup33);
        detailGroup33.setLayout(detailGroup33Layout);
        detailGroup33Layout.setHorizontalGroup(
            detailGroup33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup33Layout.createSequentialGroup()
                .addGroup(detailGroup33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailGroup33Layout.createSequentialGroup()
                        .addComponent(jTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel248)
                    .addComponent(jLabel249))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        detailGroup33Layout.setVerticalGroup(
            detailGroup33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup33Layout.createSequentialGroup()
                .addComponent(jLabel249)
                .addGap(20, 20, 20)
                .addComponent(jLabel248, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField50, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel250.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel250.setText("Course");

        jLabel251.setText("Select Course");

        jComboBox75.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 1", "Course 2", "Course 3" }));

        javax.swing.GroupLayout detailGroup34Layout = new javax.swing.GroupLayout(detailGroup34);
        detailGroup34.setLayout(detailGroup34Layout);
        detailGroup34Layout.setHorizontalGroup(
            detailGroup34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox75, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup34Layout.createSequentialGroup()
                .addComponent(jLabel250)
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(detailGroup34Layout.createSequentialGroup()
                .addComponent(jLabel251)
                .addGap(0, 199, Short.MAX_VALUE))
        );
        detailGroup34Layout.setVerticalGroup(
            detailGroup34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup34Layout.createSequentialGroup()
                .addComponent(jLabel250)
                .addGap(20, 20, 20)
                .addComponent(jLabel251, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel252.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel252.setText("Subject");

        jLabel253.setText("Select Course Subject");

        jComboBox101.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subject 1", "Subject 2", "Subject 3" }));

        javax.swing.GroupLayout detailGroup35Layout = new javax.swing.GroupLayout(detailGroup35);
        detailGroup35.setLayout(detailGroup35Layout);
        detailGroup35Layout.setHorizontalGroup(
            detailGroup35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox101, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailGroup35Layout.createSequentialGroup()
                .addGroup(detailGroup35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel253)
                    .addComponent(jLabel252))
                .addGap(0, 163, Short.MAX_VALUE))
        );
        detailGroup35Layout.setVerticalGroup(
            detailGroup35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup35Layout.createSequentialGroup()
                .addComponent(jLabel252)
                .addGap(20, 20, 20)
                .addComponent(jLabel253)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox101, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jLabel254.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel254.setText("Class");

        jLabel255.setText("Select Class");

        jButton34.setText("Find");

        jTextField51.setText("Tyep Class ID");

        javax.swing.GroupLayout detailGroup36Layout = new javax.swing.GroupLayout(detailGroup36);
        detailGroup36.setLayout(detailGroup36Layout);
        detailGroup36Layout.setHorizontalGroup(
            detailGroup36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup36Layout.createSequentialGroup()
                .addGroup(detailGroup36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel255)
                    .addComponent(jLabel254))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(detailGroup36Layout.createSequentialGroup()
                .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton34, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );
        detailGroup36Layout.setVerticalGroup(
            detailGroup36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup36Layout.createSequentialGroup()
                .addComponent(jLabel254)
                .addGap(20, 20, 20)
                .addComponent(jLabel255)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel256.setFont(new java.awt.Font("Raleway Thin", 1, 20)); // NOI18N
        jLabel256.setText("Reports");

        jLabel257.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel257.setText("Bison");

        jLabel258.setText("Batch:");

        jLabel259.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel259.setText("Nethmina Sandaruwan");

        jLabel260.setText("Student Name:");

        jLabel261.setText("Select Student");

        jComboBox102.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jComboBox103.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        jComboBox104.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox105.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class 1", "Class 2", "Class 3" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel261)
                        .addGap(350, 350, 350)
                        .addComponent(jComboBox104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox103, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox102, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel260)
                                    .addComponent(jLabel259))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel258)
                                    .addComponent(jLabel257)))
                            .addComponent(jLabel256))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jComboBox105, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel256)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel261, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox104, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox103, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox102, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jComboBox105, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel260)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel258)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel257)))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout ReportsPanelBody1Layout = new javax.swing.GroupLayout(ReportsPanelBody1);
        ReportsPanelBody1.setLayout(ReportsPanelBody1Layout);
        ReportsPanelBody1Layout.setHorizontalGroup(
            ReportsPanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsPanelBody1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(ReportsPanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ReportsPanelBody1Layout.createSequentialGroup()
                        .addComponent(detailGroup33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(detailGroup34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(detailGroup35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(detailGroup36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        ReportsPanelBody1Layout.setVerticalGroup(
            ReportsPanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsPanelBody1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(ReportsPanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(detailGroup35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailGroup34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailGroup33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailGroup36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        ReportsScrollPane1.setViewportView(ReportsPanelBody1);

        javax.swing.GroupLayout ReportsTabbedPaneRoot1Layout = new javax.swing.GroupLayout(ReportsTabbedPaneRoot1);
        ReportsTabbedPaneRoot1.setLayout(ReportsTabbedPaneRoot1Layout);
        ReportsTabbedPaneRoot1Layout.setHorizontalGroup(
            ReportsTabbedPaneRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportsTabbedPaneRoot1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ReportsScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ReportsTabbedPaneRoot1Layout.setVerticalGroup(
            ReportsTabbedPaneRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportsTabbedPaneRoot1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(ReportsScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ReportsTabbedPane.addTab("Student", ReportsTabbedPaneRoot1);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane41.setViewportView(jTable9);

        javax.swing.GroupLayout ReportsPanelBody2Layout = new javax.swing.GroupLayout(ReportsPanelBody2);
        ReportsPanelBody2.setLayout(ReportsPanelBody2Layout);
        ReportsPanelBody2Layout.setHorizontalGroup(
            ReportsPanelBody2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsPanelBody2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        ReportsPanelBody2Layout.setVerticalGroup(
            ReportsPanelBody2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsPanelBody2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        ReportsScrollPane2.setViewportView(ReportsPanelBody2);

        javax.swing.GroupLayout ReportsTabbedPaneRoot2Layout = new javax.swing.GroupLayout(ReportsTabbedPaneRoot2);
        ReportsTabbedPaneRoot2.setLayout(ReportsTabbedPaneRoot2Layout);
        ReportsTabbedPaneRoot2Layout.setHorizontalGroup(
            ReportsTabbedPaneRoot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportsTabbedPaneRoot2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ReportsScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ReportsTabbedPaneRoot2Layout.setVerticalGroup(
            ReportsTabbedPaneRoot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportsTabbedPaneRoot2Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(ReportsScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ReportsTabbedPane.addTab("History", ReportsTabbedPaneRoot2);

        javax.swing.GroupLayout ReportsPanelLayout = new javax.swing.GroupLayout(ReportsPanel);
        ReportsPanel.setLayout(ReportsPanelLayout);
        ReportsPanelLayout.setHorizontalGroup(
            ReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReportsPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ReportsPanelLayout.createSequentialGroup()
                .addComponent(ReportsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ReportsPanelLayout.setVerticalGroup(
            ReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsPanelLayout.createSequentialGroup()
                .addComponent(ReportsPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ReportsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1329, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ReportsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ReportsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ReportsPanel;
    private javax.swing.JPanel ReportsPanelBody1;
    private javax.swing.JPanel ReportsPanelBody2;
    private javax.swing.JPanel ReportsPanelHeader;
    private javax.swing.JScrollPane ReportsScrollPane1;
    private javax.swing.JScrollPane ReportsScrollPane2;
    private javax.swing.JTabbedPane ReportsTabbedPane;
    private javax.swing.JPanel ReportsTabbedPaneRoot1;
    private javax.swing.JPanel ReportsTabbedPaneRoot2;
    private javax.swing.JPanel detailGroup33;
    private javax.swing.JPanel detailGroup34;
    private javax.swing.JPanel detailGroup35;
    private javax.swing.JPanel detailGroup36;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JComboBox<String> jComboBox101;
    private javax.swing.JComboBox<String> jComboBox102;
    private javax.swing.JComboBox<String> jComboBox103;
    private javax.swing.JComboBox<String> jComboBox104;
    private javax.swing.JComboBox<String> jComboBox105;
    private javax.swing.JComboBox<String> jComboBox75;
    private javax.swing.JLabel jLabel242;
    private javax.swing.JLabel jLabel247;
    private javax.swing.JLabel jLabel248;
    private javax.swing.JLabel jLabel249;
    private javax.swing.JLabel jLabel250;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JLabel jLabel253;
    private javax.swing.JLabel jLabel254;
    private javax.swing.JLabel jLabel255;
    private javax.swing.JLabel jLabel256;
    private javax.swing.JLabel jLabel257;
    private javax.swing.JLabel jLabel258;
    private javax.swing.JLabel jLabel259;
    private javax.swing.JLabel jLabel260;
    private javax.swing.JLabel jLabel261;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    // End of variables declaration//GEN-END:variables
}
