/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.ScrollPaneConstants;

/**
 *
 * @author sandaruwan
 */
public class Teacher extends javax.swing.JPanel {

    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        TeacherScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);      
        TeacherScrollPane2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        TeacherPanel = new javax.swing.JPanel();
        TeacherPanelHeader1 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        TeacherTabbedPane = new javax.swing.JTabbedPane();
        TeacherScrollPaneRoot1 = new javax.swing.JPanel();
        TeacherScrollPane2 = new javax.swing.JScrollPane();
        TeacherPanelBody2 = new javax.swing.JPanel();
        detailGroup17 = new javax.swing.JPanel();
        jTextField59 = new javax.swing.JTextField();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jLabel163 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        jLabel164 = new javax.swing.JLabel();
        jTextField60 = new javax.swing.JTextField();
        jLabel165 = new javax.swing.JLabel();
        jTextField61 = new javax.swing.JTextField();
        jLabel166 = new javax.swing.JLabel();
        jTextField62 = new javax.swing.JTextField();
        jLabel167 = new javax.swing.JLabel();
        jTextField63 = new javax.swing.JTextField();
        jLabel168 = new javax.swing.JLabel();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jLabel169 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jTextField66 = new javax.swing.JTextField();
        detailGroup18 = new javax.swing.JPanel();
        jLabel173 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        jTextField67 = new javax.swing.JTextField();
        jLabel176 = new javax.swing.JLabel();
        jLabel177 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jLabel178 = new javax.swing.JLabel();
        jTextField68 = new javax.swing.JTextField();
        jLabel179 = new javax.swing.JLabel();
        jTextField69 = new javax.swing.JTextField();
        jLabel180 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jLabel181 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        detailGroup19 = new javax.swing.JPanel();
        jLabel183 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jLabel186 = new javax.swing.JLabel();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTextArea25 = new javax.swing.JTextArea();
        jLabel189 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTextArea26 = new javax.swing.JTextArea();
        jLabel190 = new javax.swing.JLabel();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTextArea27 = new javax.swing.JTextArea();
        jLabel192 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        detailGroup20 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jTextField72 = new javax.swing.JTextField();
        jLabel191 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        TeacherScrollPaneRoot2 = new javax.swing.JPanel();
        TeacherScrollPane1 = new javax.swing.JScrollPane();
        TeacherPanelBody1 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jLabel49.setFont(new java.awt.Font("Raleway Thin", 1, 24)); // NOI18N
        jLabel49.setText("Teachers Management");

        jLabel50.setText("Optimizing Teachers Management: Add, Remove, Update, and Search with Ease");

        javax.swing.GroupLayout TeacherPanelHeader1Layout = new javax.swing.GroupLayout(TeacherPanelHeader1);
        TeacherPanelHeader1.setLayout(TeacherPanelHeader1Layout);
        TeacherPanelHeader1Layout.setHorizontalGroup(
            TeacherPanelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelHeader1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeacherPanelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50)
                    .addComponent(jLabel49))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TeacherPanelHeader1Layout.setVerticalGroup(
            TeacherPanelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelHeader1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel161.setText("Teacher ID");

        jLabel162.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel162.setText("Identification Details");

        buttonGroup3.add(jRadioButton17);
        jRadioButton17.setText("Male");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton18);
        jRadioButton18.setText("Female");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        jLabel163.setText("Gender");

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Sri Colombo", "Matara", "Kurunegala", "Gampaha", "Kandy" }));

        jLabel164.setText("City");

        jLabel165.setText("Address");

        jLabel166.setText("Mobile");

        jLabel167.setText("Email");

        jLabel168.setText("Dat of Birth");

        jLabel169.setText("First Name");

        jLabel170.setText("Last Name");

        jLabel171.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel171.setText("Personal Informations");

        jLabel172.setText("NIC");

        javax.swing.GroupLayout detailGroup17Layout = new javax.swing.GroupLayout(detailGroup17);
        detailGroup17.setLayout(detailGroup17Layout);
        detailGroup17Layout.setHorizontalGroup(
            detailGroup17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailGroup17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(detailGroup17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel172)
                    .addComponent(jLabel171)
                    .addComponent(jTextField59)
                    .addComponent(jLabel161)
                    .addComponent(jLabel162)
                    .addGroup(detailGroup17Layout.createSequentialGroup()
                        .addComponent(jRadioButton17)
                        .addGap(50, 50, 50)
                        .addComponent(jRadioButton18))
                    .addComponent(jLabel163)
                    .addComponent(jComboBox13, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel164)
                    .addComponent(jTextField60)
                    .addComponent(jLabel165)
                    .addComponent(jTextField61)
                    .addComponent(jTextField62)
                    .addComponent(jLabel166)
                    .addComponent(jLabel167)
                    .addComponent(jLabel168)
                    .addComponent(jTextField63)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailGroup17Layout.createSequentialGroup()
                        .addGroup(detailGroup17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel169))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(detailGroup17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel170)
                            .addComponent(jTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField66)))
        );
        detailGroup17Layout.setVerticalGroup(
            detailGroup17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup17Layout.createSequentialGroup()
                .addComponent(jLabel171)
                .addGap(30, 30, 30)
                .addGroup(detailGroup17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel169, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel170))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel168)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel167)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel166)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel165)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel164)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel163)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton18))
                .addGap(30, 30, 30)
                .addComponent(jLabel162)
                .addGap(20, 20, 20)
                .addComponent(jLabel161)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField59, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel172, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel173.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel173.setText("Educational Background");

        jLabel174.setText("Highest level of education attained");

        jLabel175.setText("Year of graduation ");

        jLabel176.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel176.setText("Teaching Experience");

        jLabel177.setText("Degrees, certifications, or qualifications");

        jTextArea21.setColumns(20);
        jTextArea21.setRows(5);
        jScrollPane21.setViewportView(jTextArea21);

        buttonGroup2.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jRadioButton19.setText("Yes");

        buttonGroup2.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jRadioButton20.setText("No");

        jTextArea22.setColumns(20);
        jTextArea22.setRows(5);
        jScrollPane22.setViewportView(jTextArea22);

        jLabel178.setText("Institution(s) attended");

        jLabel179.setText("Previous teaching positions held");

        jLabel180.setText("Years of experience");

        jTextArea23.setColumns(20);
        jTextArea23.setRows(5);
        jScrollPane23.setViewportView(jTextArea23);

        jLabel181.setText("Subjects or courses taught");

        jLabel182.setText("<html>Educational institutions or organizations <br>worked at</html>");

        jTextArea24.setColumns(20);
        jTextArea24.setRows(5);
        jScrollPane24.setViewportView(jTextArea24);

        javax.swing.GroupLayout detailGroup18Layout = new javax.swing.GroupLayout(detailGroup18);
        detailGroup18.setLayout(detailGroup18Layout);
        detailGroup18Layout.setHorizontalGroup(
            detailGroup18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup18Layout.createSequentialGroup()
                .addGroup(detailGroup18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel173)
                    .addComponent(jLabel174)
                    .addComponent(jLabel176)
                    .addComponent(jLabel177)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(detailGroup18Layout.createSequentialGroup()
                        .addComponent(jRadioButton19)
                        .addGap(50, 50, 50)
                        .addComponent(jRadioButton20))
                    .addComponent(jLabel178)
                    .addComponent(jScrollPane22)
                    .addComponent(jTextField67)
                    .addComponent(jTextField68)
                    .addComponent(jLabel179)
                    .addComponent(jLabel175)
                    .addComponent(jLabel180)
                    .addComponent(jTextField69)
                    .addComponent(jLabel181)
                    .addComponent(jScrollPane23)
                    .addComponent(jLabel182, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane24))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        detailGroup18Layout.setVerticalGroup(
            detailGroup18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup18Layout.createSequentialGroup()
                .addComponent(jLabel173)
                .addGap(30, 30, 30)
                .addComponent(jLabel174)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailGroup18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20))
                .addGap(20, 20, 20)
                .addComponent(jLabel177)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel178)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel175)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel176)
                .addGap(20, 20, 20)
                .addComponent(jLabel179)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel180)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField69, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel181)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel182, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel183.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel183.setText("Specializations and Skills");

        jLabel184.setText("Current employment status");

        jLabel185.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel185.setText("Employment Information");

        buttonGroup1.add(jRadioButton21);
        jRadioButton21.setText("Full-Time");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton22);
        jRadioButton22.setText("Part-Time");

        jLabel186.setText("Subject area");

        jLabel187.setText("Employment start date");

        jLabel188.setText("Specializations in specific subjects");

        jTextArea25.setColumns(20);
        jTextArea25.setRows(5);
        jScrollPane25.setViewportView(jTextArea25);

        jLabel189.setText("Teaching methodologies or approaches");

        jTextArea26.setColumns(20);
        jTextArea26.setRows(5);
        jScrollPane26.setViewportView(jTextArea26);

        jLabel190.setText("Additional skills or expertise");

        jTextArea27.setColumns(20);
        jTextArea27.setRows(5);
        jScrollPane27.setViewportView(jTextArea27);

        jLabel192.setFont(new java.awt.Font("Raleway Thin", 1, 16)); // NOI18N
        jLabel192.setText("Consent and Permissions");

        jCheckBox6.setText("<html>Consent for background checks or <br>verification processesr</html>");
        jCheckBox6.setIconTextGap(12);

        jCheckBox7.setText("<html>Consent for the use of personal <br> information for administrative purposes</html>");
        jCheckBox7.setIconTextGap(12);

        javax.swing.GroupLayout detailGroup19Layout = new javax.swing.GroupLayout(detailGroup19);
        detailGroup19.setLayout(detailGroup19Layout);
        detailGroup19Layout.setHorizontalGroup(
            detailGroup19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailGroup19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(detailGroup19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox6)
                    .addComponent(jLabel192)
                    .addComponent(jLabel190)
                    .addComponent(jLabel189)
                    .addComponent(jLabel188)
                    .addComponent(jLabel187)
                    .addComponent(jLabel186)
                    .addGroup(detailGroup19Layout.createSequentialGroup()
                        .addComponent(jRadioButton21)
                        .addGap(50, 50, 50)
                        .addComponent(jRadioButton22))
                    .addComponent(jLabel185)
                    .addComponent(jLabel183)
                    .addComponent(jLabel184)
                    .addComponent(jTextField70, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jTextField71)
                    .addComponent(jScrollPane26)
                    .addComponent(jScrollPane27)
                    .addComponent(jScrollPane25)
                    .addComponent(jCheckBox7, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
        );
        detailGroup19Layout.setVerticalGroup(
            detailGroup19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup19Layout.createSequentialGroup()
                .addComponent(jLabel185)
                .addGap(20, 20, 20)
                .addComponent(jLabel184)
                .addGap(12, 12, 12)
                .addGroup(detailGroup19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton22))
                .addGap(20, 20, 20)
                .addComponent(jLabel186)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel187)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel192)
                .addGap(20, 20, 20)
                .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel183)
                .addGap(20, 20, 20)
                .addComponent(jLabel188)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel189)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel190)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton13.setText("Add New Teacher");

        jButton14.setText("Update Teacher Details");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Remove Teacher");

        jTextField72.setText("Search Teachers");
        jTextField72.setToolTipText("Search Students");

        jLabel191.setText("Select Teacher (To Edit Details)");

        javax.swing.GroupLayout detailGroup20Layout = new javax.swing.GroupLayout(detailGroup20);
        detailGroup20.setLayout(detailGroup20Layout);
        detailGroup20Layout.setHorizontalGroup(
            detailGroup20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(jTextField72, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addGroup(detailGroup20Layout.createSequentialGroup()
                .addComponent(jLabel191)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        detailGroup20Layout.setVerticalGroup(
            detailGroup20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailGroup20Layout.createSequentialGroup()
                .addComponent(jLabel191)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(606, 606, 606))
        );

        jSeparator6.setForeground(new java.awt.Color(65, 77, 87));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout TeacherPanelBody2Layout = new javax.swing.GroupLayout(TeacherPanelBody2);
        TeacherPanelBody2.setLayout(TeacherPanelBody2Layout);
        TeacherPanelBody2Layout.setHorizontalGroup(
            TeacherPanelBody2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelBody2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(detailGroup17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(detailGroup18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(detailGroup19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(detailGroup20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        TeacherPanelBody2Layout.setVerticalGroup(
            TeacherPanelBody2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelBody2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(TeacherPanelBody2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeacherPanelBody2Layout.createSequentialGroup()
                        .addComponent(detailGroup19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(TeacherPanelBody2Layout.createSequentialGroup()
                        .addGroup(TeacherPanelBody2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(detailGroup17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(detailGroup18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(detailGroup20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(TeacherPanelBody2Layout.createSequentialGroup()
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TeacherScrollPane2.setViewportView(TeacherPanelBody2);

        javax.swing.GroupLayout TeacherScrollPaneRoot1Layout = new javax.swing.GroupLayout(TeacherScrollPaneRoot1);
        TeacherScrollPaneRoot1.setLayout(TeacherScrollPaneRoot1Layout);
        TeacherScrollPaneRoot1Layout.setHorizontalGroup(
            TeacherScrollPaneRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TeacherScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
        );
        TeacherScrollPaneRoot1Layout.setVerticalGroup(
            TeacherScrollPaneRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherScrollPaneRoot1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TeacherScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TeacherTabbedPane.addTab("Edit", TeacherScrollPaneRoot1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane12.setViewportView(jTable2);

        javax.swing.GroupLayout TeacherPanelBody1Layout = new javax.swing.GroupLayout(TeacherPanelBody1);
        TeacherPanelBody1.setLayout(TeacherPanelBody1Layout);
        TeacherPanelBody1Layout.setHorizontalGroup(
            TeacherPanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelBody1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        TeacherPanelBody1Layout.setVerticalGroup(
            TeacherPanelBody1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelBody1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        TeacherScrollPane1.setViewportView(TeacherPanelBody1);

        javax.swing.GroupLayout TeacherScrollPaneRoot2Layout = new javax.swing.GroupLayout(TeacherScrollPaneRoot2);
        TeacherScrollPaneRoot2.setLayout(TeacherScrollPaneRoot2Layout);
        TeacherScrollPaneRoot2Layout.setHorizontalGroup(
            TeacherScrollPaneRoot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TeacherScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
        );
        TeacherScrollPaneRoot2Layout.setVerticalGroup(
            TeacherScrollPaneRoot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherScrollPaneRoot2Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(TeacherScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TeacherTabbedPane.addTab("View Details", TeacherScrollPaneRoot2);

        javax.swing.GroupLayout TeacherPanelLayout = new javax.swing.GroupLayout(TeacherPanel);
        TeacherPanel.setLayout(TeacherPanelLayout);
        TeacherPanelLayout.setHorizontalGroup(
            TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TeacherPanelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addComponent(TeacherTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        TeacherPanelLayout.setVerticalGroup(
            TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addComponent(TeacherPanelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TeacherTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1349, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TeacherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 951, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TeacherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TeacherPanel;
    private javax.swing.JPanel TeacherPanelBody1;
    private javax.swing.JPanel TeacherPanelBody2;
    private javax.swing.JPanel TeacherPanelHeader1;
    private javax.swing.JScrollPane TeacherScrollPane1;
    private javax.swing.JScrollPane TeacherScrollPane2;
    private javax.swing.JPanel TeacherScrollPaneRoot1;
    private javax.swing.JPanel TeacherScrollPaneRoot2;
    private javax.swing.JTabbedPane TeacherTabbedPane;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel detailGroup17;
    private javax.swing.JPanel detailGroup18;
    private javax.swing.JPanel detailGroup19;
    private javax.swing.JPanel detailGroup20;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea25;
    private javax.swing.JTextArea jTextArea26;
    private javax.swing.JTextArea jTextArea27;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    // End of variables declaration//GEN-END:variables
}
